disabled = false
languageCode = "zh-CN"
languageName = "简体中文"
weight = 1
title = ""

[params]
  displayName = "简体中文"
  isoCode = "cn"
  rtl = false
  dateFormat = ":date_medium"
  logo = "img/Logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "George 的个人博客"
  copyright = "Copyright &copy; 2024 - 2025 <a href=\"https://github.com/GeorgeC6\" target=\"_blank\" rel=\"noopener noreferrer\">George Cao</a>"

[params.author]
  name = "George"
  email = "georgecao@zju.edu.cn"
  image = "img/Profile_Pic.png"
  imageQuality = 96
  headline = ""
  bio = ""
  links = [
    { email = "mailto:georgecao@zju.edu.cn" },
    # { link = "https://link-to-some-website.com/" },
    # { discord = "https://discord.gg/invitecode" },
    # { facebook = "https://facebook.com/username" },
    { github = "https://github.com/GeorgeC6" },
    # { instagram = "https://instagram.com/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { orcid = "https://orcid.org/userid" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    { soundcloud = "https://soundcloud.com/gorco" },
    # { spotify = "https://open.spotify.com/user/userid" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    # { steam = "https://steamcommunity.com/profiles/userid" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://www.threads.net/@username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { x-twitter = "https://twitter.com/username" },
    # { whatsapp = "https://wa.me/phone-number" },
    { youtube = "https://youtube.com/@gorcomusic" },
  ]
