site_name: G-log
site_author: George Cao
site_url: https://blog.gorco.me/
site_description: George's Blog -> G-log

copyright: Copyright &copy; 2024 - 2025 <a href="https://github.com/GeorgeC6" target="_blank" rel="noopener noreferrer">George Cao</a>

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: images/favicon.ico
  icon:
    logo: George Sig.
    repo: fontawesome/brands/github
    tag:
      thesis: material/file-document
      physics: material/atom
      math: material/function-variant
      code: fontawesome/solid/code
  custom_dir: overrides
  features:
    # - header.autohide # 向下滚动时自动隐藏header
    - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    # - navigation.tabs
    - navigation.top
    - navigation.indexes  # 点击小节名字自动显示 index 界面
    - navigation.footer # 底部导航栏
    # - navigation.instant # 站内瞬移，但会导致公式跳转后不渲染
    - navigation.instant.progress
    - toc.integrate   # 文档 toc 集成到总目录中
    - toc.follow  # 右侧目录跟随滚动
    - search.highlight
    - search.share
    - search.suggest
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - announce.dismiss

  palette:
    - media: "(prefers-color-scheme: light)"  # 浅色模式
      scheme: default
      primary: light-blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"   # 深色模式
      scheme: slate
      primary: deep-purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/GeorgeC6
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@gorcomusic
    - icon: fontawesome/brands/soundcloud
      link: https://soundcloud.com/gorco
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/413263041
    - icon: material/forum-outline
      link: https://www.cc98.org/user/id/733259

  analytics:
    provider: google
    property: G-200PC48K70

  tags:
    课程论文: thesis
    微积分: math
    量子力学: physics
    编程技术: code

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.tilde
  - pymdownx.mark:
      smart_mark: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - footnotes
  - md_in_html
  - attr_list
  - toc:
      permalink: true
      toc_depth: 4

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true # 好像能加快网页加载速度？!
  - tags
  - meta
  - blog:
      blog_dir: .
      blog_toc: true
      post_date_format: long
  - rss:
      enabled: !ENV [CI, false]
      match_path: /posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
      comments_path: "#__comments"
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"

extra_javascript:
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js   # MathJax 3

extra_css:
  - stylesheets/extra.css
  - stylesheets/custom.css

nav:
  - 主页: "index.md"
  - 标签: "tags.md"